language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r dev_requirements.txt

script:
  - python -m coverage run -m pytest

script:
  - python -m coverage report
