language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r dev_requirements.txt

script:
  - pylint_runner
  - python -m coverage run -m pytest
  - python -m coverage report
